### ISSUE TITLE
Steam won't launch after creating new directory

### ISSUE THREAD

**Issue by pfled** [LostDragonist/steam-library-setup-tool#3]
Getting error "failed to load steamui.dll" when attempting to launch after using the program for the first time

**Comment by LostDragonist** [comment]
Does your Steam installation contain SteamUI.dll? The default location is `C:\Program Files (x86)\Steam`.  If not, you have a corrupt Steam install and... I guess you should delete everything in that folder except Steam.exe and the steamapps folder and run Steam.exe again?

Otherwise, you can go into your steamapps folder (default location "C:\Program Files (x86)\Steam\steamapps"), delete libraryfolders.vdf, and rename libraryfolders.vdf.bak to libraryfolders.vdf.  This will undo all the changes this program makes to your Steam install.  

If that works... /shrug.  I guess it might help if you upload the broken lbiraryfolders.vdf?  The only thing I can imagine is that you tried to set some weird path that either my tool or Steam doesn't support.
